### ISSUE TITLE
ValueError: authenticator must be provided

### ISSUE THREAD

**Issue by SarathChandra24** [IBM/watson-voice-bot#51]
(mytestenv) C:\Users\Sarat\ana\watson-voice-bot>python app.py
INFO:engineio.server:Server initialized for threading.
Traceback (most recent call last):
  File "app.py", line 128, in <module>
    assistant = AssistantV1(version="2019-11-06", authenticator=authenticator)
  File "C:\Users\Sarat\ana\watson-voice-bot\mytestenv\lib\site-packages\ibm_watson\assistant_v1.py", line 81, in __init__
    disable_ssl_verification=disable_ssl_verification)
  File "C:\Users\Sarat\ana\watson-voice-bot\mytestenv\lib\site-packages\ibm_cloud_sdk_core\base_service.py", line 63, in __init__
    raise ValueError('authenticator must be provided')
ValueError: authenticator must be provided

**Comment by markstur** [comment]
authenticator is set from the environment right before that call L126.
So if it is not set, that probably means you did not set your .env file to have either
ASSISTANT_APIKEY=<your key>
ASSISTANT_URL=<your url>
